[package]
name = "yagbas_ssa"
description = "Yagbas single-static-assignment crate."
repository = "https://github.com/Lokathor/yagbas"
homepage = "https://lokathor.github.io/yagbas/"
license = "Zlib OR Apache-2.0 OR MIT"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
