[package]
name = "yagbas_asmtypes"
description = "The assembly data type for the yagbas compiler."
repository = "https://github.com/Lokathor/yagbas"
license = "Zlib OR Apache-2.0 OR MIT"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
str_id = "0.1.0"
