name: Yagbas Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      toolchain: 1.85.0
    
    - name: yagbas tests
      run: cargo test

    - name: yagbas_asmtypes tests
      run: cd yagbas_asmtypes && cargo test

    - name: yagbas_srcfiletypes tests
      run: cd yagbas_srcfiletypes && cargo test

    - name: yagbas_asttypes tests
      run: cd yagbas_asttypes && cargo test
